apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcpo-time.fullname" . }}
  labels:
    {{- include "mcpo-time.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Values.config | toPrettyJson  | indent 4 }}
