apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: open-webui
  namespace: kube-system
spec:
  repo: https://helm.openwebui.com/
  chart: open-webui
  targetNamespace: open-webui
  createNamespace: true
  version: 12.5.0
  valuesContent: |-
    ollama:
      enabled: false
    ollamaUrls: http://ollama.ollama.svc.cluster.local:11434
    ingress:
      enabled: true
      class: "traefik"
      host: "open-webui.lab.systemj.net"
      tls: true
      existingSecret: "lab-systemj-net-wildcard"
    extraEnvVars:
      - name: ENABLE_RAG_LOCAL_WEB_FETCH
        value: "true"
