apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: sabertooth
spec:
  tags:
  - "tag:k8s"
  hostnamePrefix: sabertooth
  replicas: 1
  subnetRouter:
    advertiseRoutes:
    - "192.168.86.0/24"
  exitNode: true
